# Generated by Django 6.0.6 on 2026-06-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_performance_reservation_ticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/plays/"),
        ),
    ]
